# combined_model_runner.py

from app.firework_client import run_firework_model
from app.openai_client import run_openai_model

def generate_response(prompt):
    """Attempt Firework first, fallback to OpenAI if Firework fails."""
    firework_response = run_firework_model(prompt)
    if firework_response:
        print("✅ Response generated by Firework.")
        return firework_response
    
    print("⚠️ Firework failed. Falling back to OpenAI...")
    openai_response = run_openai_model(prompt)
    if openai_response:
        print("✅ Response generated by OpenAI.")
        return openai_response
    
    print("❌ Both Firework and OpenAI failed.")
    return None

if __name__ == "__main__":
    prompt = "Say hello from GrayBot!"
    response = generate_response(prompt)
    if response:
        print(f"\nResponse:\n{response}")
    else:
        print("\nNo response could be generated.")
